# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{http-load-tester}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Clarke"]
  s.date = %q{2010-01-24}
  s.default_executable = %q{http-load-tester}
  s.email = %q{tom.clarke@u2i.com}
  s.executables = ["http-load-tester"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/http-load-tester.rb",
     "lib/http-load-tester/callbacks.rb",
     "lib/http-load-tester/dsl.rb",
     "lib/http-load-tester/dsl/main.rb",
     "lib/http-load-tester/scenario.rb",
     "lib/http-load-tester/scenario_factory.rb",
     "lib/http-load-tester/tester.rb"
  ]
  s.homepage = %q{http://github.com/pinetops/http-load-tester}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{HTTP Load Testing DSL}
  s.test_files = [
    "spec/http-load-tester_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<httpclient>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<httpclient>, [">= 0"])
  end
end

